### ISSUE TITLE
Text blocks since Java 15 not Java 11

### ISSUE THREAD

**Issue by ivanocj** [marchof/io.javaalmanac.snippets#3]
https://github.com/marchof/io.javaalmanac.snippets/blob/ac6cb39f3254aa7ba6def428d39fe51b40f5707f/src/main/java/io/javaalmanac/snippets/io/ReadWriteTextFiles.java#L16

**Comment by marchof** [comment]
Thanks, fixed: f9adf40d679a9eacc6df2bf4e9b59bef5b2ef0cc
